### ISSUE TITLE
create footer

### ISSUE THREAD

**Issue by ankit-c11** [ankit-c11/Daksh#2]
footer would have social media links and  web developers page/profile link

**Comment by ankit-c11** [comment]
fb: https://www.facebook.com/teamdaksh.nitjsr/
insta: https://instagram.com/team.daksh?utm_source=ig_profile_share&igshid=w3n0m7q4lqr9

**Comment by ankit-c11** [comment]
youtube: https://youtu.be/IGEeijM46tI

**Comment by ankit-c11** [comment]
https://www.me.vt.edu/Teams/baja-team/ 
refer this for footer

**Comment by aryan2574** [comment]
Footer Created. Pull the code.
