### ISSUE TITLE
Create body of the webpage.

### ISSUE THREAD

**Issue by ankit-c11** [ankit-c11/Daksh#3]
https://dakshnitjsr.wixsite.com/teamdaksh

take text matter from here... i have also added resources in the public directory for images

**Comment by ankit-c11** [comment]
[Daksh Brochure.pdf](https://github.com/ankit-c11/Daksh/files/4484526/Daksh.Brochure.pdf)

Text matter can be taken from this as well

**Comment by aryan2574** [comment]
The changes you made is not looking good. Consider changing it or add something new.
