### ISSUE TITLE
Create sponsors page

### ISSUE THREAD

**Issue by ankit-c11** [ankit-c11/Daksh#4]
the page will have details related to sponsorship

**Comment by ankit-c11** [comment]
[Sponsorship Brochure.docx](https://github.com/ankit-c11/Daksh/files/4484666/Sponsorship.Brochure.docx)


 details can be taken from this docx

**Comment by aryan2574** [comment]
I'm on it.

**Comment by ankit-c11** [comment]
[Sponsorship Brochure.pdf](https://github.com/ankit-c11/Daksh/files/4496856/Sponsorship.Brochure.pdf)

**Comment by ankit-c11** [comment]
[sponsors.zip](https://github.com/ankit-c11/Daksh/files/4537175/sponsors.zip)

here are the sponsors logo

**Comment by ankit-c11** [comment]
![1587892120228 (1)](https://user-images.githubusercontent.com/45822513/80330134-fc0ae880-8861-11ea-8255-6e0e85dccc88.png)
one more
